import { createAction } from '@reduxjs/toolkit';
import { AppRoute, AuthorizationStatus } from '../const';
import { Comments } from '../types/comment';
import { Film, Films } from '../types/film';

export const setAvatar = createAction<string>('data/setAvatar');
export const selectGenre = createAction<{ genre: string }>('genre/selectGenre');
export const getSortedFilmsList = createAction('films/getSortedFilmsList');
export const loadFilms = createAction<Films>('data/loadFilms');
export const loadSimilar = createAction<Films>('data/loadSimilar');
export const loadOneFilm = createAction<Film>('data/loadOneFilm');
export const cleanOneFilm = createAction('data/cleanOneFilm');
export const loadPromo = createAction<Film>('data/loadPromo');
export const loadFavorite = createAction<Films>('data/loadFavorite');
export const loadComments = createAction<Comments>('data/loadComments');
export const setCommentError = createAction<string>('user/setCommentError');
export const setDataLoadingStatus = createAction<boolean>('data/setDataLoadingStatus');
export const setFilmLoadingStatus = createAction<boolean>('data/setFilmLoadingStatus');
export const requireAuthorization = createAction<AuthorizationStatus>('user/requireAuthorization');
export const redirectToRoute = createAction<AppRoute | string>('user/redirectToRoute');
export const setLoginError = createAction<string>('user/setLoginError');
